---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: fabric8-tenant-user
    provider: fabric8
    version: ${COMMIT}
  name: fabric8-tenant-user
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${NAMESPACE_PREFIX}
      openshift.io/display-name: ${NAMESPACE_PREFIX}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      provider: fabric8
      project: fabric8-online-user
      version: ${COMMIT}
    name: ${NAMESPACE_PREFIX}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
    labels:
      app: jenkins
      provider: fabric8
      expose: "false"
      version: ${COMMIT}
    name: jenkins
    namespace: ${NAMESPACE_PREFIX}
  spec:
    externalName: jenkins.${NAMESPACE_PREFIX}-jenkins
    ports:
    - name: http
      port: 80
    selector:
      app: fabric8-tenant-user
      provider: fabric8
    type: ExternalName
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: jenkins-edit
    namespace: ${NAMESPACE_PREFIX}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${NAMESPACE_PREFIX}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: jenkins-view
    namespace: ${NAMESPACE_PREFIX}
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${NAMESPACE_PREFIX}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: user-edit
    namespace: ${NAMESPACE_PREFIX}
  roleRef:
    name: edit
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: user-view
    namespace: ${NAMESPACE_PREFIX}
  roleRef:
    name: view
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      description: Defines the environments used by your Continuous Delivery pipelines.
      fabric8.console/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg
    labels:
      kind: environments
      provider: fabric8
      app: fabric8-tenant-user
      version: ${COMMIT}
    name: fabric8-environments
    namespace: ${NAMESPACE_PREFIX}
  data:
    test: |-
      name: Test
      namespace: ${NAMESPACE_PREFIX}
      order: 0
    stage: |-
      name: Stage
      namespace: ${NAMESPACE_PREFIX}-stage
      order: 1
    run: |-
      name: Run
      namespace: ${NAMESPACE_PREFIX}-run
      order: 2
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/target-platform: openshift
    labels:
      app: fabric8-tenant-user
      provider: fabric8
      version: ${COMMIT}
    name: fabric8-pipelines
    namespace: ${NAMESPACE_PREFIX}
  data:
    fabric8-console-url: ${FABRIC8_CONSOLE_URL}
    keycloak-url: ${KEYCLOAK_URL}
    ci-branch-patterns: '- PR-.*'
    cd-branch-patterns: '- master'
    disable-itests-cd: "false"
    disable-itests-ci: "false"
    use-docker-socket: "false"
parameters:
- name: NAMESPACE_PREFIX
  value: developer
- name: PROJECT_ADMIN_USER
  value: developer
- name: PROJECT_REQUESTING_USER
  value: system:admin
- name: EXTERNAL_DOCKER_REGISTRY_URL
- name: FABRIC8_CONSOLE_URL
- name: KEYCLOAK_URL
- name: COMMIT
  value: 123abc