---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: fabric8-tenant-${DEPLOY_TYPE}
    provider: fabric8
    version: ${COMMIT}
  name: fabric8-tenant-${DEPLOY_TYPE}
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${USER_NAME} ${DEPLOY_TYPE} Environment
      openshift.io/display-name: ${USER_NAME} ${DEPLOY_TYPE}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: ${USER_NAME}-${DEPLOY_TYPE}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: dsaas-access-sa-ns
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  spec:
    serviceaccountrestriction:
      namespaces:
      - ${USER_NAME}-jenkins
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: dsaas-user-access
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  spec:
    userrestriction:
      users:
      - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: jenkins-edit
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${USER_NAME}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: jenkins-view
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: jenkins
  userNames:
  - system:serviceaccount:${USER_NAME}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: user-edit
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  roleRef:
    name: edit
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      app: fabric8-tenant-${DEPLOY_TYPE}
      provider: fabric8
      version: ${COMMIT}
    name: user-view
    namespace: ${USER_NAME}-${DEPLOY_TYPE}
  roleRef:
    name: view
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
parameters:
- name: USER_NAME
  value: developer
- name: DEPLOY_TYPE
  value: run
- name: PROJECT_NAME
  value: myproject
- name: PROJECT_ADMIN_USER
  value: developer
- name: PROJECT_REQUESTING_USER
  value: system:admin
- name: COMMIT
  value: 123abc
