---
apiVersion: v1
kind: Template
metadata:
  labels:
    app: fabric8-tenant
    provider: fabric8
    version: ${COMMIT}
objects:
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
        app: fabric8-tenant
        provider: fabric8
        version: ${COMMIT}
    name: dsaas-access-users
  spec: 
    userrestriction:
      users: 
      - ${PROJECT_ADMIN_USER}
      - system:serviceaccount:${NAMESPACE_PREFIX}-jenkins:jenkins
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
        app: fabric8-tenant
        provider: fabric8
        version: ${COMMIT}
    name: dsaas-access-groups
  spec: 
    grouprestriction:
      groups: 
      - system:serviceaccounts:${NAMESPACE_PREFIX}-jenkins
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    labels:
        app: fabric8-tenant
        provider: fabric8
        version: ${COMMIT}
    name: dsaas-access-sa-ns
  spec: 
    serviceaccountrestriction:
      namespaces: 
      - ${NAMESPACE_PREFIX}-jenkins
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
        app: fabric8-tenant
        provider: fabric8
        version: ${COMMIT}
    name: dsaas-admin
    namespace: ${NAMESPACE_PREFIX}
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_ADMIN_USER}
  userNames:
  - ${PROJECT_ADMIN_USER}
parameters:
- name: NAMESPACE_PREFIX
  value: developer
- name: PROJECT_ADMIN_USER
  value: developer
- name: COMMIT
  value: 123abc